.TH GMEMO 1 "May 2003" "FlashCode"

.SH NAME
gmemo \- memo applet for XFree

.SH SYNOPSIS
.B gmemo
.RI [ options ]
.br

.SH DESCRIPTION
gmemo is a memo applet for XFree, which can be run as a window maker/fluxbox
applet, in the Gnome panel or as standalone program.

.SH OPTIONS
.TP
.B \-d, \-\-daemon
.br
run gmemo as a daemon (no display, Linux only)
.TP
.B \-h, \-\-help
.br
this help screen
.TP
.B \-l, \-\-licence
.br
display program licence
.TP
.B \-q, \-\-quiet
.br
doesn't display any message
.TP
.B \-s, \-\-seconds
.br
display seconds
.TP
.B \-v, \-\-verbose
.br
verbose mode
.TP
.B \-w, \-\-withdrawn
.br
runs gmemo in withdrawn mode (for slit or window maker, Linux only)

.SH FILES
.TP
.B $HOME/.gmemo/gmemo_feasts.xml
contains feasts for each day
.TP
.B $HOME/.gmemo/gmemo.xml
memo file

.SH SEE ALSO
.BR gmemo_gnome (1)

.SH AUTHOR
Gmemo is written by FlashCode <flashcode@flashtux.org>
and Quetzalcoatl <damien.cassou@laposte.net>
.br
Gmemo on the web:
.UR
http://gmemo.flashtux.org
.UE
