.TH GMEMO 1 "May 2003" "FlashCode"

.SH NAME
gmemo_gnome \- memo applet for XFree (Gnome panel)

.SH SYNOPSIS
.B gmemo
.RI [ options ]
.br

.SH DESCRIPTION
gmemo_gnome is a memo applet for Gnome panel (see gmemo man page for detail)

.SH FILES
.TP
.B $HOME/.gmemo/gmemo_feasts.xml
contains feasts for each day
.TP
.B $HOME/.gmemo/gmemo.xml
memo file

.SH SEE ALSO
.BR gmemo (1)

.SH AUTHOR
Gmemo is written by FlashCode <flashcode@flashtux.org>
and Quetzalcoatl <damien.cassou@laposte.net>
.br
Gmemo on the web:
.UR
http://gmemo.flashtux.org
.UE
